### PR TITLE
8 gradle incremental builds

### LINKED ISSUE #8: Feature request gradle incremental builds
I think this gradle plugin is already awesome and easy to use.

But it would be great if it sported gradle incremental builds to make builds faster.
https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks

Currently I use this configuration to implement them my self.
```kotlin
val minify by tasks
minify.apply {
    inputs.dir("$buildDir/minify/src/js") // here you could use jsSrcDir from configuration
    inputs.dir("$buildDir/minify/src/css") // here you could use cssSrcDir from configuration
    outputs.dir("$buildDir/minify/dst/js") // here you could use jsDstDir from configuration
    outputs.dir("$buildDir/minify/dst/css") // here you could use cssDstDir from configuration
}
```
or in a more project independent way
```kotlin
val minify by tasks
minify.apply {
    inputs.dir(jsSrcDir)
    inputs.dir(cssSrcDir)
    outputs.dir(jsDstDir)
    outputs.dir(cssDstDir)
}
```

The configuration could then look like this.
```kotlin
minification {
    jsSrcDir = "$buildDir/minify/src/js"
    jsDstDir = "$buildDir/minify/dst/js"
    cssSrcDir = "$buildDir/minify/src/css"
    cssDstDir = "$buildDir/minify/dst/css"

    incrementalBuilds = true // default should be true
}
```

### PR DESCRIPTION
**Pull request by timon-schelling**
used docs https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks

### CODE REVIEW

**Comment by 616slayer616** [comment]
Looks nice.
I tried something similar don't know what I was doing wrong and it told me it couldn't find the properties.

But when I run the task twice in a row it tells me:

```
20:29:09: Executing task 'minify'...

> Task :minify

BUILD SUCCESSFUL in 13s
1 actionable task: 1 executed
20:29:23: Task execution finished 'minify'.
```

I would have thought it would say UP TO DATE on the second run.

**Comment by timon-schelling** [comment]
Thanks.
With my changes it should be UP-TO-DATE on the second run.

**Comment by 616slayer616** [comment]
Did it work for you locally?

**Comment by timon-schelling** [comment]
Yes

**Comment by 616slayer616** [comment]
Ok.
I will look further into this. Maybe my configuration is the problem.

Your TODO "consider using a explicit disable option of both css and js compiling in plugin extension" does not really fit to this feature.
If you want we can do it separately.

I will merge this.

Do you want to release it aswell?

**Review by 616slayer616 — APPROVED** [review]

**Comment by timon-schelling** [comment]
Yes, sorry.

And a release would be awesome. 

Maybe as preview release?

**Comment by 616slayer616** [comment]
Nothing to be sorry about.
I will release 1.4.0-SNAPSHOT

**Pull request merged**
